In [1]:
import pymongo as mg
import pandas as pd

In [2]:
client = mg.MongoClient(host='mongodb://localhost:27017')

In [4]:
database = client['db_medicals']

In [5]:
collection = database['RecurrenceOfSurgery']

In [6]:
cursor = collection.find({})
data_list = list(cursor)

In [13]:
df_ros = pd.DataFrame(data_list)
df_ros.head(10)

,_id,Unnamed: 0,환자ID,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,...,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추이동척도,척추전방위증
0,64d33aec3103df69b8578dcc,0,1PT,22.8,3,51.0,0.0,0,0,0,...,3,51.6,36.6,14.40,0,-1.01,2048.50,4,Down,0
1,64d33aec3103df69b8578dcd,1,2PT,44.9,4,26.0,0.0,0,0,0,...,0,40.8,7.2,17.80,0,-1.14,1753.10,4,Up,0
2,64d33aec3103df69b8578dce,2,3PT,53.0,3,NaN,0.0,0,0,1,...,0,67.5,27.3,10.20,0,-1.77,1749.00,4,Down,0
3,64d33aec3103df69b8578dcf,3,4PT,54.7,4,18.0,0.0,0,1,0,...,0,49.2,18.7,19.90,0,-1.58,1796.20,4,Down,0
4,64d33aec3103df69b8578dd0,4,5PT,53.8,4,NaN,0.0,0,1,0,...,0,58.8,14.7,5.20,0,-0.79,2021.48,4,Up,0
5,64d33aec3103df69b8578dd1,5,6PT,28.5,3,NaN,0.0,0,0,2,...,0,41.8,23.6,8.80,0,-0.95,1937.50,4,Down,0
6,64d33aec3103df69b8578dd2,6,7PT,4.2,3,NaN,0.0,0,0,0,...,0,41.9,17.4,1.53,1,-1.71,2466.90,4,Down,0
7,64d33aec3103df69b8578dd3,7,8PT,43.8,4,NaN,0.0,0,0,0,...,0,50.6,18.5,10.70,0,-1.04,1830.58,4,Middle,0
8,64d33aec3103df69b8578dd4,8,9PT,89.0,3,31.0,0.0,0,0,0,...,0,48.8,13.6,13.80,1,-1.33,2021.75,4,Down,0
9,64d33aec3103df69b8578dd5,9,10PT,40.5,3,NaN,0.0,0,0,0,...,0,38.9,14.7,14.20,0,-2.51,2302.50,4,Middle,0

In [11]:
df_ros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1894 entries, 0 to 1893
Data columns (total 53 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   _id                     1894 non-null   object
 1   Unnamed: 0              1894 non-null   int64
 2   환자ID                    1894 non-null   object
 3   Large Lymphocyte        1894 non-null   float64
 4   Location of herniation  1894 non-null   int64
 5   ODI                     462 non-null    float64
 6   가족력                     1843 non-null   float64
 7   간질성폐질환                  1894 non-null   int64
 8   고혈압여부                   1894 non-null   int64
 9   과거수술횟수                  1894 non-null   int64
 10  당뇨여부                    1894 non-null   int64
 11  말초동맥질환여부                1894 non-null   int64
 12  빈혈여부                    1894 non-null   int64
 13  성별                      1894 non-null   int64
 14  스테로이드치료                 1894 non-null   int64
 15  신부전여부                   1894 non-null   int64
 16  신장                      1894 non-null   int64
 17  심혈관질환                   1894 non-null   int64
 18  암발병여부                   1894 non-null   int64
 19  연령                      1894 non-null   int64
 20  우울증여부                   1894 non-null   int64
 21  입원기간                    1894 non-null   int64
 22  입원일자                    1894 non-null   int64
 23  종양진행여부                  1894 non-null   int64
 24  직업                      1479 non-null   object
 25  체중                      1894 non-null   float64
 26  퇴원일자                    1894 non-null   int64
 27  헤모글로빈수치                 1893 non-null   float64
 28  혈전합병증여부                 1894 non-null   int64
 29  환자통증정도                  1894 non-null   int64
 30  흡연여부                    1894 non-null   int64
 31  통증기간(월)                 1890 non-null   float64
 32  수술기법                    1813 non-null   object
 33  수술시간                    1840 non-null   float64
 34  수술실패여부                  1894 non-null   int64
 35  수술일자                    1894 non-null   int64
 36  재발여부                    1894 non-null   int64
 37  혈액형                     1894 non-null   object
 38  전방디스크높이(mm)             1894 non-null   float64
 39  후방디스크높이(mm)             1894 non-null   float64
 40  지방축적도                   1891 non-null   float64
 41  Instability             1894 non-null   int64
 42  MF + ES                 1894 non-null   float64
 43  Modic change            1894 non-null   int64
 44  PI                      1890 non-null   float64
 45  PT                      1890 non-null   float64
 46  Seg Angle(raw)          1893 non-null   float64
 47  Vaccum disc             1894 non-null   int64
 48  골밀도                     998 non-null    float64
 49  디스크단면적                  1893 non-null   float64
 50  디스크위치                   1894 non-null   int64
 51  척추이동척도                  1894 non-null   object
 52  척추전방위증                  1894 non-null   int64
dtypes: float64(16), int64(31), object(6)
memory usage: 784.4+ KB

In [12]:
df_ros.columns

Index(['_id', 'Unnamed: 0', '환자ID', 'Large Lymphocyte',
       'Location of herniation', 'ODI', '가족력', '간질성폐질환', '고혈압여부', '과거수술횟수',
       '당뇨여부', '말초동맥질환여부', '빈혈여부', '성별', '스테로이드치료', '신부전여부', '신장', '심혈관질환',
       '암발병여부', '연령', '우울증여부', '입원기간', '입원일자', '종양진행여부', '직업', '체중', '퇴원일자',
       '헤모글로빈수치', '혈전합병증여부', '환자통증정도', '흡연여부', '통증기간(월)', '수술기법', '수술시간',
       '수술실패여부', '수술일자', '재발여부', '혈액형', '전방디스크높이(mm)', '후방디스크높이(mm)', '지방축적도',
       'Instability', 'MF + ES', 'Modic change', 'PI', 'PT', 'Seg Angle(raw)',
       'Vaccum disc', '골밀도', '디스크단면적', '디스크위치', '척추이동척도', '척추전방위증'],
      dtype='object')

In [19]:
df_ros_drops = df_BND.drop(columns=['_id', 'Unnamed: 0', 'Large Lymphocyte',
       'Location of herniation', 'ODI', '가족력', '간질성폐질환', '과거수술횟수', '스테로이드치료', '신장', '입원기간', '입원일자', '종양진행여부', '직업', '체중', '퇴원일자',
       '헤모글로빈수치', '혈전합병증여부', '환자통증정도', '통증기간(월)', '수술일자', '혈액형', 'Instability', 'MF + ES', 'Modic change', 'PI', 'PT', 'Seg Angle(raw)',
       'Vaccum disc', '골밀도', '디스크단면적', '디스크위치',])
df_ros_drops.head(10)

,환자ID,고혈압여부,당뇨여부,말초동맥질환여부,빈혈여부,성별,신부전여부,심혈관질환,암발병여부,연령,...,흡연여부,수술기법,수술시간,수술실패여부,재발여부,전방디스크높이(mm),후방디스크높이(mm),지방축적도,척추이동척도,척추전방위증
0,1PT,0,0,0,0,2,0,0,0,66,...,0,TELD,68.0,0,0,16.1,12.3,282.30,Down,0
1,2PT,0,0,0,0,1,0,0,0,47,...,0,TELD,31.0,0,0,13.7,6.4,177.30,Up,0
2,3PT,0,0,0,0,1,0,0,0,39,...,0,TELD,78.0,0,0,13.6,7.4,256.80,Down,0
3,4PT,1,0,0,0,1,0,0,0,40,...,0,TELD,73.0,0,0,10.6,7.3,250.10,Down,0
4,5PT,1,0,0,0,1,0,0,0,42,...,0,TELD,29.0,0,0,17.1,8.1,232.20,Up,0
5,6PT,0,0,1,0,2,0,0,0,60,...,1,TELD,47.0,0,0,12.8,10.7,129.90,Down,0
6,7PT,0,1,0,0,1,0,0,0,47,...,0,TELD,7.0,0,0,12.2,8.4,177.30,Down,0
7,8PT,0,0,0,0,1,0,0,0,55,...,1,TELD,85.0,0,0,14.1,8.6,161.02,Middle,0
8,9PT,0,0,0,0,1,0,0,0,52,...,1,TELD,49.0,0,0,14.7,7.5,157.21,Down,0
9,10PT,0,0,0,0,1,0,0,0,79,...,0,TELD,59.0,1,0,17.9,9.6,127.10,Middle,0

In [20]:
df_ros_drops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1894 entries, 0 to 1893
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   환자ID         1894 non-null   object
 1   고혈압여부        1894 non-null   int64
 2   당뇨여부         1894 non-null   int64
 3   말초동맥질환여부     1894 non-null   int64
 4   빈혈여부         1894 non-null   int64
 5   성별           1894 non-null   int64
 6   신부전여부        1894 non-null   int64
 7   심혈관질환        1894 non-null   int64
 8   암발병여부        1894 non-null   int64
 9   연령           1894 non-null   int64
 10  우울증여부        1894 non-null   int64
 11  흡연여부         1894 non-null   int64
 12  수술기법         1813 non-null   object
 13  수술시간         1840 non-null   float64
 14  수술실패여부       1894 non-null   int64
 15  재발여부         1894 non-null   int64
 16  전방디스크높이(mm)  1894 non-null   float64
 17  후방디스크높이(mm)  1894 non-null   float64
 18  지방축적도        1891 non-null   float64
 19  척추이동척도       1894 non-null   object
 20  척추전방위증       1894 non-null   int64
dtypes: float64(4), int64(14), object(3)
memory usage: 310.9+ KB

In [21]:
df_ros_drops.describe()

,고혈압여부,당뇨여부,말초동맥질환여부,빈혈여부,성별,신부전여부,심혈관질환,암발병여부,연령,우울증여부,흡연여부,수술시간,수술실패여부,재발여부,전방디스크높이(mm),후방디스크높이(mm),지방축적도,척추전방위증
count,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1840.000000,1894.000000,1894.000000,1894.000000,1894.000000,1891.000000,1894.000000
mean,0.130940,0.062830,0.004224,0.024287,1.383316,0.025343,0.035903,0.013728,41.463569,0.023231,0.217001,62.066304,0.060718,0.119852,11.382635,8.358126,241.524289,0.032207
std,0.337424,0.242721,0.064871,0.153980,0.486323,0.157207,0.186097,0.116388,13.444629,0.154143,0.412312,24.994615,0.238875,0.324874,2.852451,4.244340,445.211922,0.176596
min,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,15.000000,0.000000,0.000000,5.000000,0.000000,0.000000,1.270000,1.000000,25.970000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,32.000000,0.000000,0.000000,45.000000,0.000000,0.000000,9.540000,7.100000,121.145000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,41.000000,0.000000,0.000000,60.000000,0.000000,0.000000,11.200000,8.300000,169.100000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,49.000000,0.000000,0.000000,77.000000,0.000000,0.000000,13.200000,9.500000,251.800000,0.000000
max,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,86.000000,2.000000,1.000000,220.000000,1.000000,1.000000,22.500000,101.000000,12113.470000,1.000000

In [22]:
df_ros_drops.describe(include=object)

        환자ID  수술기법  척추이동척도
count   1894  1813    1894
unique  1894     2       5
top      1PT  TELD  Middle
freq       1  1673    1260

In [23]:
df_ros_drops['수술실패여부'].value_counts()

0    1779
1     115
Name: 수술실패여부, dtype: int64

In [24]:
df_ros_drops['수술실패여부'].unique()

array([0, 1], dtype=int64)